name: Deployment to alex server 2
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-and-push:
    runs-on: [self-hosted, benson img]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push seeded images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mythical_inventory_images:latest -t ${{ secrets.DOCKERHUB_USERNAME }}/mythical_inventory_images:${{ github.run_number }} .
          docker push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/mythical_inventory_images
